#spring:
#  zipkin:
#    base-url: http://192.168.1.108:9411
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      probability: 1.0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.1.108:8849
#    gateway:
#      routes:
#        - id: demo-order-service
#          uri: lb://demo-order-service
#          #uri: http://localhost:8001
#          order: 1
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - StripPrefix=1
#        - id: demo-video-service
#          uri: lb://demo-video-service
#          #uri: http://localhost:8003
#          order: 1
#          predicates:
#            - Path=/video-service/**
#          filters:
#            - StripPrefix=1
#      discovery:
#        locator:
#          enabled: true